version: '3.7'

services:
  database:
    image: postgres:16-alpine
    environment: 
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: admin
      POSTGRES_DB: metrics
    ports:
      - 8080:5432
    volumes:
      - metrics-pgsql-data:/var/lib/postgresql/data

volumes:
  metrics-pgsql-data:
